"""DRISHTI traversability: a learned off-road drivability / risk head.

What this stage answers
----------------------
A detector answers "what object is this?".  This stage answers "can *this vehicle*
drive here?" - which is a different question, because the answer depends on the
vehicle envelope in ``CFG.ugv`` (clearance, max step, width, max slope), not on the
object category.  The same patch of grass is SAFE for a 0.30 m-clearance platform and
OBSTACLE for the 0.045 m-clearance RC chassis this footage was shot from.

Supervision - read this before quoting any number
-------------------------------------------------
There is **no human traversability annotation** anywhere in this repo, and no
RELLIS-3D / GOOSE / ORFD ground truth is available offline.  The network is trained on
**geometric + semantic pseudo-labels** generated by
``drishti/training/make_trav_labels.py`` from
  * metric height above the **local** ground surface, ground slope and roughness
    (``local_terrain_fields`` below, on top of ``perception/geometry.py``; scale
    anchored on the *assumed* camera height ``CFG.cam.height_above_ground_m``), and
  * the DRISHTI-7 terrain segmentation (itself distilled from an ADE20K teacher).
Every accuracy number reported for this stage is therefore **agreement with those
pseudo-labels**, never accuracy against ground truth.  Say it that way.

Why learn it at all, if the labels are rules?
---------------------------------------------
Three concrete reasons, all of which show up in the output videos:
  1. The rules need *clean* metric depth.  The network sees RGB as well, so it keeps
     producing a sane map where the depth fit degrades (dusk / low light clips).
  2. The rules are per-pixel and speckly; a conv decoder with an ImageNet trunk
     produces spatially coherent regions and interpolates across depth dropouts.
  3. Distilling into one small shared trunk gives one cheap forward pass that serves
     both traversability *and* uncertainty - which is what makes the CPU story real.

Architecture
------------
``SharedPerceptionTrunk``  MobileNetV3-Small (torchvision ImageNet weights, cached
locally) with an inflated 17-channel stem + a light top-down FPN to stride 4.
It is deliberately **shared** with ``models/uncertainty.py`` - one trunk, two thin
heads - because the contract asks for shared backbones for CPU efficiency.

Input stack (17 channels, at ``NET_W x NET_H`` = 320x180), documented exactly:
  0-2   RGB, ImageNet mean/std normalised.  **Absolute** normalisation, deliberately
        not per-frame contrast normalised, so a low-light frame stays dark and the
        uncertainty head can actually see the illumination it is meant to distrust.
  3     inverse depth      clip(0.5 / D_metres, 0, 1)        (0.5 m -> 1.0, 5 m -> 0.10)
  4     height above LOCAL ground  clip(h, -0.45, 0.90) / 0.90  (metres, + above grade)
  5     ground slope       clip(slope_deg, 0, 45) / 45
  6     roughness          clip(local height std, 0, 0.10) / 0.10   (metres)
  7     geometry valid     1 where metric depth + ground fit are usable
  8-14  DRISHTI-7 terrain one-hot (sky, trail, grass, rough_veg, obstacle, water, dynamic)
  15    segmentation max probability
  16    segmentation normalised entropy

Heads: 3x3 -> BN -> Hardswish -> two 1x1 convs, giving a 4-class logit map
(safe / risky / obstacle / unknown) and a 1-channel continuous risk regression.
"""
from __future__ import annotations

import time
from pathlib import Path
from typing import Optional

import cv2
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

from ..config import (CFG, CKPT_DIR, N_TERRAIN, N_TRAV, PROC_H, PROC_W,
                      SAFE, RISKY, OBSTACLE, UNKNOWN)
from ..io_utils import ego_mask
from ..perception import geometry as G
from ..types import FramePacket, TraversabilityResult

# --------------------------------------------------------------------------- constants

NET_W, NET_H = 320, 180          # network working resolution (exactly PROC / 2)
IN_CH = 17                       # see module docstring
FPN_CH = 48                      # decoder width
CKPT_PATH = CKPT_DIR / "trav_unc_shared.pt"

FEAT_NAMES = (
    "rgb_r", "rgb_g", "rgb_b",
    "inv_depth", "height_m", "slope_deg", "roughness_m", "geo_valid",
    "terr_sky", "terr_trail", "terr_grass", "terr_rough_veg",
    "terr_obstacle", "terr_water", "terr_dynamic",
    "seg_pmax", "seg_entropy",
)
assert len(FEAT_NAMES) == IN_CH

_IMAGENET_MEAN = np.array([0.485, 0.456, 0.406], np.float32)
_IMAGENET_STD = np.array([0.229, 0.224, 0.225], np.float32)

INV_D_REF = 0.5      # metres; feature 3 is clip(INV_D_REF / D, 0, 1)
H_LO, H_HI = -0.45, 0.90
SLOPE_REF = 45.0
ROUGH_REF = 0.10

# Channels that must be resized with NEAREST (one-hot / masks) rather than blended.
_NEAREST_CH = tuple(range(7, 15))


# --------------------------------------------------------------------------- features

def _nz(a: np.ndarray) -> np.ndarray:
    return np.nan_to_num(np.asarray(a, np.float32), nan=0.0, posinf=0.0, neginf=0.0)


def build_feature_stack(rgb_bgr: np.ndarray,
                        depth_m: np.ndarray,
                        valid: np.ndarray,
                        height: np.ndarray,
                        slope_deg: np.ndarray,
                        rough: np.ndarray,
                        seg_label: np.ndarray,
                        seg_pmax: np.ndarray,
                        seg_entropy: np.ndarray) -> np.ndarray:
    """Assemble the documented 17-channel input stack at the input array resolution.

    Everything is expected at the same (H, W).  Returns (17, H, W) float32.
    """
    h, w = depth_m.shape[:2]
    out = np.zeros((IN_CH, h, w), np.float32)

    rgb = cv2.cvtColor(rgb_bgr, cv2.COLOR_BGR2RGB).astype(np.float32) / 255.0
    out[0:3] = ((rgb - _IMAGENET_MEAN) / _IMAGENET_STD).transpose(2, 0, 1)

    d = _nz(depth_m)
    with np.errstate(divide="ignore", invalid="ignore"):
        inv = np.where(d > 1e-3, INV_D_REF / np.maximum(d, 1e-3), 0.0)
    out[3] = np.clip(_nz(inv), 0.0, 1.0)

    out[4] = np.clip(_nz(height), H_LO, H_HI) / H_HI
    out[5] = np.clip(_nz(slope_deg), 0.0, SLOPE_REF) / SLOPE_REF
    out[6] = np.clip(_nz(rough), 0.0, ROUGH_REF) / ROUGH_REF
    out[7] = np.asarray(valid, bool).astype(np.float32)

    lab = np.asarray(seg_label, np.int32)
    for c in range(N_TERRAIN):
        out[8 + c] = (lab == c).astype(np.float32)

    out[15] = np.clip(_nz(seg_pmax), 0.0, 1.0)
    out[16] = np.clip(_nz(seg_entropy), 0.0, 1.0)

    # Kill everything the vehicle body / watermark covers: it is not scene geometry.
    em = ego_mask(h, w)
    out[3:8] *= em
    return out


def resize_stack(stack: np.ndarray, size=(NET_W, NET_H)) -> np.ndarray:
    """Resize a (C,H,W) feature stack to (w,h), NEAREST for one-hot/mask channels."""
    c = stack.shape[0]
    out = np.empty((c, size[1], size[0]), np.float32)
    for i in range(c):
        interp = cv2.INTER_NEAREST if i in _NEAREST_CH else cv2.INTER_AREA
        out[i] = cv2.resize(stack[i], size, interpolation=interp)
    return out


def local_terrain_fields(points_veh: np.ndarray, valid: np.ndarray,
                         win_m: float = 0.90):
    """Height above the **local** support surface, and the slope of that surface.

    ``geometry.height_slope_roughness`` returns height above the single fitted ground
    *plane* and a per-pixel slope.  Measured on this footage, both are too noisy to be
    compared against a 3 cm vehicle step: the plane drifts a few centimetres over a 7 m
    look-ahead, and the per-pixel slope reads a ~10-14 deg median on a *flat* gravel
    path.  Either one alone would label most of a drivable trail as an obstacle.

    So the ground surface is re-estimated in **metric BEV space** (an image-space window
    covers wildly different ground areas at 0.5 m and at 6 m):

      1. average the observed height per BEV cell;
      2. take the mean over a ``win_m`` neighbourhood, then re-take it using only cells
         at or below that mean + half a max-step.  One robust re-weighting pass, so a
         kerb inside the window does not drag the ground reference up with it, and -
         unlike a plain min-filter - depth noise does not drag it down either;
      3. height above local ground = z - reference;
      4. ground slope = the gradient of that reference surface, in metres per metre.

    Pixels outside the BEV footprint keep height above the fitted plane and the
    image-space slope.  Returns ``(h_local, slope_deg)``.
    """
    z = points_veh[..., 2].astype(np.float32)
    vm = np.asarray(valid, bool) & np.isfinite(z)
    h_plane = np.where(vm, z, np.nan).astype(np.float32)
    slope_img = robust_slope_deg(points_veh, vm)
    row, col, keep = G.bev_indices(points_veh, vm)
    if keep.sum() < 50:
        return h_plane, slope_img

    b = CFG.bev
    # bincount, not np.add.at: the latter is ~40x slower on 200k scattered indices and
    # this runs once per frame in the live path.
    flat = (row[keep].astype(np.int64) * b.W + col[keep].astype(np.int64))
    acc = np.bincount(flat, weights=z[keep].astype(np.float64),
                      minlength=b.H * b.W).reshape(b.H, b.W).astype(np.float32)
    cnt = np.bincount(flat, minlength=b.H * b.W).reshape(b.H, b.W).astype(np.float32)
    occ = cnt > 0
    cell = np.where(occ, acc / np.maximum(cnt, 1.0), 0.0).astype(np.float32)

    k = max(3, int(round(win_m / b.res_m)) | 1)          # 0.90 m -> 15 cells
    def _box(a):
        return cv2.boxFilter(a.astype(np.float32), -1, (k, k), normalize=False)

    occf = occ.astype(np.float32)
    d1 = _box(occf)
    mean1 = _box(cell * occf) / np.maximum(d1, 1.0)
    low = (occ & (cell <= mean1 + 0.5 * CFG.ugv.max_step_m)).astype(np.float32)
    d2 = _box(low)
    ref = np.where(d2 > 2.0, _box(cell * low) / np.maximum(d2, 1.0), mean1).astype(np.float32)

    gx = cv2.Sobel(ref, cv2.CV_32F, 1, 0, ksize=3) / (8.0 * b.res_m)
    gy = cv2.Sobel(ref, cv2.CV_32F, 0, 1, ksize=3) / (8.0 * b.res_m)
    slope_bev = np.degrees(np.arctan(np.clip(np.hypot(gx, gy), 0, 20))).astype(np.float32)
    slope_bev = cv2.blur(slope_bev, (5, 5))
    seen = d1 > 0

    h_out = h_plane.copy()
    s_out = slope_img.copy()
    idx = np.nonzero(keep)
    ok = seen[row[keep], col[keep]]
    h_out[idx[0][ok], idx[1][ok]] = z[keep][ok] - ref[row[keep], col[keep]][ok]
    s_out[idx[0][ok], idx[1][ok]] = slope_bev[row[keep], col[keep]][ok]
    return h_out.astype(np.float32), s_out.astype(np.float32)



def local_roughness(points_veh: np.ndarray, valid: np.ndarray, win: int = 9) -> np.ndarray:
    """Local height standard deviation in metres - the roughness channel.

    Identical to the roughness half of ``geometry.height_slope_roughness``; it is
    recomputed here only so the per-frame path does not also pay for that function's
    slope estimator, which this module replaces with ``local_terrain_fields``.
    """
    z = points_veh[..., 2].astype(np.float32)
    m = np.asarray(valid, bool).astype(np.float32)
    filled = np.nan_to_num(z, nan=0.0) * m
    k = (win, win)
    den = cv2.boxFilter(m, -1, k, normalize=False)
    mean = cv2.boxFilter(filled, -1, k, normalize=False) / np.maximum(den, 1.0)
    var = np.maximum(cv2.boxFilter(filled ** 2, -1, k, normalize=False)
                     / np.maximum(den, 1.0) - mean ** 2, 0.0)
    rough = np.sqrt(var).astype(np.float32)
    rough[den < 6] = np.nan
    return rough


def robust_slope_deg(points_veh: np.ndarray, valid: np.ndarray, win: int = 11) -> np.ndarray:
    """Surface slope in degrees, computed on a validity-weighted smoothed height field.

    Same estimator as ``geometry.height_slope_roughness`` (dz/dx, dz/dy in metric vehicle
    coordinates) but the fields are box-smoothed first and the Sobel is 5x5, because the
    raw per-pixel version reads ~12 deg median on a *flat* gravel path - pure monocular
    depth noise - which would trip a 13 deg risk threshold over the whole scene.
    """
    m = np.asarray(valid, bool).astype(np.float32)
    k = (win, win)
    den = cv2.boxFilter(m, -1, k, normalize=False)

    def _sm(a):
        num = cv2.boxFilter(np.nan_to_num(a, nan=0.0).astype(np.float32) * m, -1, k,
                            normalize=False)
        return num / np.maximum(den, 1.0)

    zs, xs, ys = _sm(points_veh[..., 2]), _sm(points_veh[..., 0]), _sm(points_veh[..., 1])
    gz_u = cv2.Sobel(zs, cv2.CV_32F, 1, 0, ksize=5)
    gz_v = cv2.Sobel(zs, cv2.CV_32F, 0, 1, ksize=5)
    gx_u = cv2.Sobel(xs, cv2.CV_32F, 1, 0, ksize=5)
    gy_v = cv2.Sobel(ys, cv2.CV_32F, 0, 1, ksize=5)
    dzdx = gz_u / np.where(np.abs(gx_u) < 1e-3, np.nan, gx_u)
    dzdy = gz_v / np.where(np.abs(gy_v) < 1e-3, np.nan, gy_v)
    grad = np.sqrt(np.nan_to_num(dzdx) ** 2 + np.nan_to_num(dzdy) ** 2)
    slope = np.degrees(np.arctan(np.clip(grad, 0, 20))).astype(np.float32)
    slope = cv2.medianBlur(slope, 5)
    slope[den < 6] = np.nan
    return slope


def geometry_from_depth(depth_m: np.ndarray, valid: np.ndarray, fit: "G.GroundFit"):
    """(height above LOCAL ground, slope deg, roughness m, points_veh) from metric depth.

    ``height`` is what ``types.GeometryResult.height_above_ground`` documents: metres
    above local ground, not above the global fitted plane.
    """
    pts_cam = G.unproject(np.nan_to_num(depth_m, nan=0.0))
    pts_veh = G.to_vehicle(pts_cam, fit)
    rough = local_roughness(pts_veh, valid)
    h_local, slope = local_terrain_fields(pts_veh, valid)
    return h_local, slope, rough, pts_veh


# --------------------------------------------------------------------------- trunk

class _SepConv(nn.Module):
    """Depthwise-separable 3x3 -> BN -> Hardswish.  Cheap FPN smoothing."""

    def __init__(self, ch: int):
        super().__init__()
        self.dw = nn.Conv2d(ch, ch, 3, 1, 1, groups=ch, bias=False)
        self.pw = nn.Conv2d(ch, ch, 1, bias=False)
        self.bn = nn.BatchNorm2d(ch)
        self.act = nn.Hardswish(inplace=True)

    def forward(self, x):
        return self.act(self.bn(self.pw(self.dw(x))))


class SharedPerceptionTrunk(nn.Module):
    """MobileNetV3-Small + light FPN, shared by the traversability and uncertainty heads.

    One instance of this object is created once and handed to both heads, so a frame
    costs exactly one backbone forward pass regardless of how many heads consume it.

    Taps (at NET_H x NET_W = 180x320):
        features[1]  ->  16 ch, stride 4   (45x80)
        features[3]  ->  24 ch, stride 8   (23x40)
        features[8]  ->  48 ch, stride 16  (12x20)
        features[12] -> 576 ch, stride 32  (6x10)
    Output: (B, FPN_CH, H/4, W/4).
    """

    TAPS = (1, 3, 8, 12)
    TAP_CH = (16, 24, 48, 576)

    def __init__(self, in_ch: int = IN_CH, fpn_ch: int = FPN_CH, pretrained: bool = True):
        super().__init__()
        from torchvision.models import mobilenet_v3_small, MobileNet_V3_Small_Weights
        w = MobileNet_V3_Small_Weights.IMAGENET1K_V1 if pretrained else None
        base = mobilenet_v3_small(weights=w)
        self.features = base.features
        self.in_ch = in_ch

        # --- inflate the RGB stem to 17 channels, keeping the ImageNet filters ---
        old = self.features[0][0]
        new = nn.Conv2d(in_ch, old.out_channels, kernel_size=old.kernel_size,
                        stride=old.stride, padding=old.padding, bias=False)
        with torch.no_grad():
            new.weight.zero_()
            new.weight[:, :3] = old.weight
            if in_ch > 3:
                # geometry/semantic channels start from a small share of the mean RGB
                # filter, so they contribute from step 0 without swamping the prior.
                seed = old.weight.mean(dim=1, keepdim=True) * 0.1
                new.weight[:, 3:] = seed.repeat(1, in_ch - 3, 1, 1)
        self.features[0][0] = new

        self.lat = nn.ModuleList([nn.Conv2d(c, fpn_ch, 1, bias=False) for c in self.TAP_CH])
        self.lat_bn = nn.ModuleList([nn.BatchNorm2d(fpn_ch) for _ in self.TAP_CH])
        self.smooth = nn.ModuleList([_SepConv(fpn_ch) for _ in range(3)])
        self.out_ch = fpn_ch

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        taps = []
        for i, blk in enumerate(self.features):
            x = blk(x)
            if i in self.TAPS:
                taps.append(x)
        c4, c8, c16, c32 = taps
        p = self.lat_bn[3](self.lat[3](c32))
        for k, c in zip((2, 1, 0), (c16, c8, c4)):
            lat = self.lat_bn[k](self.lat[k](c))
            p = F.interpolate(p, size=lat.shape[-2:], mode="bilinear", align_corners=False)
            p = self.smooth[k](p + lat)
        return p                                    # (B, fpn_ch, H/4, W/4)


# --------------------------------------------------------------------------- head

class TravHead(nn.Module):
    """Thin head: 4-class traversability logits + 1-channel continuous risk."""

    def __init__(self, in_ch: int = FPN_CH, mid: int = 48):
        super().__init__()
        self.stem = nn.Sequential(
            nn.Conv2d(in_ch, mid, 3, 1, 1, bias=False),
            nn.BatchNorm2d(mid),
            nn.Hardswish(inplace=True),
        )
        self.cls = nn.Conv2d(mid, N_TRAV, 1)
        self.risk = nn.Conv2d(mid, 1, 1)

    def forward(self, feat: torch.Tensor):
        f = self.stem(feat)
        return self.cls(f), self.risk(f)


class TraversabilityNet(nn.Module):
    """Shared trunk + traversability head.

    Pass an existing ``SharedPerceptionTrunk`` to share weights with the uncertainty
    model (that is the intended use; see ``training/train_trav_unc.py``).
    """

    def __init__(self, trunk: Optional[SharedPerceptionTrunk] = None,
                 in_ch: int = IN_CH, pretrained: bool = True):
        super().__init__()
        self.trunk = trunk if trunk is not None else SharedPerceptionTrunk(in_ch, pretrained=pretrained)
        self.head = TravHead(self.trunk.out_ch)

    def forward(self, x: torch.Tensor, out_size=None):
        feat = self.trunk(x)
        logits, risk = self.head(feat)
        size = out_size or x.shape[-2:]
        logits = F.interpolate(logits, size=size, mode="bilinear", align_corners=False)
        risk = F.interpolate(risk, size=size, mode="bilinear", align_corners=False)
        return logits, risk, feat

    # convenience -----------------------------------------------------------
    def n_params(self) -> dict:
        t = sum(p.numel() for p in self.trunk.parameters())
        h = sum(p.numel() for p in self.head.parameters())
        return {"trunk": t, "trav_head": h, "total": t + h}


# --------------------------------------------------------------------------- stage

class TraversabilityStage:
    """Contract stage: fills ``packet.trav`` with a ``TraversabilityResult``.

    Holds the shared trunk.  ``models/uncertainty.UncertaintyStage`` can be given a
    reference to this stage and will then reuse the cached trunk features for the same
    frame instead of running the backbone twice.
    """

    def __init__(self, device: str = "cuda", ckpt: Optional[Path] = None,
                 fp16: bool = True, trunk: Optional[SharedPerceptionTrunk] = None,
                 strict: bool = True):
        self.device = torch.device(device if (device == "cpu" or torch.cuda.is_available()) else "cpu")
        self.fp16 = bool(fp16) and self.device.type == "cuda"
        self.net = TraversabilityNet(trunk=trunk, pretrained=trunk is None)
        self.ckpt_path = Path(ckpt) if ckpt is not None else CKPT_PATH
        self.loaded = False
        if self.ckpt_path.exists():
            self.load(self.ckpt_path)
        elif strict:
            raise FileNotFoundError(
                f"traversability checkpoint not found: {self.ckpt_path}\n"
                "Run:  python -m drishti.training.make_trav_labels\n"
                "then: python -m drishti.training.train_trav_unc")
        self.net.to(self.device).eval()
        if self.fp16:
            self.net.half()          # done once: the trunk is shared, so it must not be
                                     # flipped to half lazily behind the other head's back
        # temporal state -----------------------------------------------------
        self._fit: Optional[G.GroundFit] = None
        self.last_feat: Optional[torch.Tensor] = None
        self.last_key: tuple = (None, -1)
        self.last_stack: Optional[np.ndarray] = None

    # -----------------------------------------------------------------------
    def load(self, path: Path) -> None:
        sd = torch.load(path, map_location="cpu", weights_only=False)
        self.net.trunk.load_state_dict(sd["trunk"])
        self.net.head.load_state_dict(sd["trav_head"])
        self.loaded = True

    def reset(self) -> None:
        self._fit = None
        self.last_feat = None
        self.last_key = (None, -1)
        self.last_stack = None

    # -----------------------------------------------------------------------
    def _stack_from_packet(self, packet: FramePacket) -> np.ndarray:
        d = packet.depth
        if d is None or packet.seg is None:
            raise ValueError("TraversabilityStage needs packet.depth and packet.seg")
        valid = d.valid if d.valid is not None else np.isfinite(d.depth_m)
        if packet.geom is not None:
            h, s, r = (packet.geom.height_above_ground, packet.geom.slope_deg,
                       packet.geom.roughness)
        else:
            fit = G.fit_metric_ground(d.rel_inv, valid, packet.seg.label, prior=self._fit)
            if not fit.ok and self._fit is not None:
                fit = self._fit
            if fit.ok:
                self._fit = fit
            h, s, r, _ = geometry_from_depth(d.depth_m, valid, fit)
        return build_feature_stack(packet.rgb, d.depth_m, valid, h, s, r,
                                   packet.seg.label, packet.seg.prob_max, packet.seg.entropy)

    @torch.no_grad()
    def __call__(self, packet: FramePacket) -> FramePacket:
        t0 = time.perf_counter()
        stack = self._stack_from_packet(packet)
        self.last_stack = stack
        H, W = stack.shape[1:]
        x = torch.from_numpy(resize_stack(stack)).unsqueeze(0).to(self.device)
        if self.fp16:
            x = x.half()
        logits, risk, feat = self.net(x, out_size=(H, W))
        prob = torch.softmax(logits.float(), 1)[0].cpu().numpy().astype(np.float32)
        risk_np = torch.sigmoid(risk.float())[0, 0].cpu().numpy().astype(np.float32)
        self.last_feat = feat
        self.last_key = (packet.clip_id, packet.idx)

        label = prob.argmax(0).astype(np.uint8)
        # the vehicle body / watermark are not scene: force UNKNOWN there
        em = ego_mask(H, W)
        label[~em] = UNKNOWN
        risk_np[~em] = 0.0
        packet.trav = TraversabilityResult(prob=prob, label=label, risk=risk_np)
        packet.timings_ms["trav"] = (time.perf_counter() - t0) * 1e3
        return packet


# --------------------------------------------------------------------------- self test

def _synth_inputs(h: int = PROC_H, w: int = PROC_W, seed: int = 0):
    """Synthetic stand-ins with the right shapes/dtypes, used before the real caches exist."""
    rng = np.random.default_rng(seed)
    rgb = rng.integers(0, 255, (h, w, 3), dtype=np.uint8)
    yy = np.linspace(0, 1, h, dtype=np.float32)[:, None] * np.ones((1, w), np.float32)
    depth = (0.4 + 6.0 * (1.0 - yy)).astype(np.float32)
    valid = np.ones((h, w), bool)
    valid[:int(0.30 * h)] = False
    height = (rng.normal(0, 0.01, (h, w)).astype(np.float32))
    height[:, int(0.7 * w):] += 0.09
    slope = np.abs(rng.normal(4, 2, (h, w))).astype(np.float32)
    rough = np.abs(rng.normal(0.006, 0.003, (h, w))).astype(np.float32)
    lab = np.ones((h, w), np.uint8)
    lab[:int(0.30 * h)] = 0
    lab[:, int(0.7 * w):] = 4
    pmax = np.full((h, w), 0.8, np.float32)
    ent = np.full((h, w), 0.2, np.float32)
    return rgb, depth, valid, height, slope, rough, lab, pmax, ent


if __name__ == "__main__":
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    a = ap.parse_args()

    print("== DRISHTI traversability self-test ==")
    stack = build_feature_stack(*_synth_inputs())
    print(f"feature stack {stack.shape} {stack.dtype}  "
          f"range [{stack.min():.2f},{stack.max():.2f}]")
    for i, n in enumerate(FEAT_NAMES):
        print(f"   {i:2d} {n:<14s} min {stack[i].min():+.3f}  max {stack[i].max():+.3f}")
    small = resize_stack(stack)
    print("net input", small.shape)

    net = TraversabilityNet()
    print("params:", net.n_params())
    assert net.n_params()["total"] < 5e6, "over the 5M budget"

    dev = torch.device(a.device)
    net = net.to(dev).eval()
    x = torch.from_numpy(small).unsqueeze(0).to(dev)
    with torch.no_grad():
        lg, rk, ft = net(x, out_size=(PROC_H, PROC_W))
    print("logits", tuple(lg.shape), "risk", tuple(rk.shape), "trunk feat", tuple(ft.shape))

    # latency
    reps = 20
    with torch.no_grad():
        for _ in range(3):
            net(x)
        if dev.type == "cuda":
            torch.cuda.synchronize()
        t0 = time.perf_counter()
        for _ in range(reps):
            net(x)
        if dev.type == "cuda":
            torch.cuda.synchronize()
    print(f"forward {(time.perf_counter()-t0)/reps*1e3:.2f} ms/frame on {dev}")
    if dev.type == "cuda":
        print(f"peak VRAM {torch.cuda.max_memory_allocated()/2**20:.0f} MB")
        torch.cuda.empty_cache()
    print("OK")
